### PR TITLE
added arrow shape type

### PR DESCRIPTION
**Pull request by psuzn**

### CODE REVIEW

**Comment by burhanrashid52** [comment]
@psuzn Thanks for the PR. Can you please add a gif or screenshot on how this arrow looks/works ?

**Comment by burhanrashid52** [comment]
@psuzn Thanks. Currently, we are converting the library into Kotlin #428 So we might need to redo these changes again in Kotlin. So I suggest waiting for the conversation to be completed and once it's merged, you can rebase with the new Kotlin code and make a PR with those changes. Sounds Good ?

**Comment by psuzn** [comment]
@burhanrashid52, I've updated this. Please have a look when you get some time.

**Comment by burhanrashid52** [comment]
@psuzn The code looks good to me. However, I've two things.
1. Can you write a test for the Arrow changes?
2. The arrow seems like a subclass of LINE. So I was thinking if we can expose a LineBuilder which have a property to allow a pointer to the start and end of the line. What do you think?

**Comment by psuzn** [comment]
@burhanrashid52, I had added a test for the enums beside that I don’t think there is a shape-specific test setup to verify the shape being drawn, is there? 

The `LineBuilder` sounds like a good idea, but I've been super busy lately and not sure I would be able to add this.

**Comment by burhanrashid52** [comment]
@psuzn No worries. You can contribute back whenever you are available. Till then I will keep this PR open as a reference for others.

**Pull request closed without merging**
