### PR TITLE
text editor

### PR DESCRIPTION
**Pull request by rtz333**

### CODE REVIEW

**Comment by rtz333** [comment]
My first time pr. sorry if there's something wrong

**Comment by burhanrashid52** [comment]
I am not able to review the changes. I see only two files with change. You need fork the latest from this project. Commit the changes and then create a PR. This video might help. https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by rtz333** [comment]
@burhanrashid52 I have some updated .hope it helps you

**Comment by burhanrashid52** [comment]
Can you please add some test. Check [TextStyleBuilderTest](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/test/java/ja/burhanrashid52/photoeditor/TextStyleBuilderTest.java) for reference.

**Comment by rtz333** [comment]
imgtest
screenshot

**Comment by burhanrashid52** [comment]
This look great. However the on test is [failing](https://github.com/burhanrashid52/PhotoEditor/blob/master/photoeditor/src/test/java/ja/burhanrashid52/photoeditor/TextStyleBuilderTest.java#L15).  This test is failing because of entries in map count. Let me know once you push the fix.

**Comment by rtz333** [comment]
@burhanrashid52  can u test again. i still dont know how to test it @@@

**Comment by burhanrashid52** [comment]
The test are failing again. Please run the unit test in local using `./gradlew tests`

**Comment by rtz333** [comment]
> The test are failing again. Please run the unit test in local using `./gradlew tests`

i think it work now.can you check it again

**Review by burhanrashid52 — APPROVED** [review]

**Pull request merged**
