### PR TITLE
This fixes Saving file on Android  10 and 11

### PR DESCRIPTION
**Pull request by tanoDxyz**
I made changes to the **saveImage** method in **Edit-Image-Activity** and also changed the language level to 1.8 and tested the 
app on both android 10 and 11 emulators and a physical device.

### CODE REVIEW

**Comment by burhanrashid52** [comment]
Need to resolve the conflicts. Also, can you just explain why using the background handler to save the image?

**Comment by tanoDxyz** [comment]
ok and why use handler to save the image ?

**Comment by tanoDxyz** [comment]
**Why to use Background Thread ?**  <br/> Actually we are dealing with database using content resolver and also we are creating a file in the main thread. adding a bit more even android has **AsyncQueryHandler** to process content resolver queries in the background. **creating a File** and **Querying database** are blocking operations and more to say that  the code works perfectly if we don't use background thread .<br/>

**Comment by burhanrashid52** [comment]
Can you showcase any other osp example on share resources on this background thread which applies to your code changes ?

**Comment by tanoDxyz** [comment]
Well first thing I used *Handler* and you know that very well - that there are a lot of different ways to write code for background execution and the **sample-app** is I believe for demonstrating the library but however </br> **Whether to use Background Thread or not For Content Resolver** </br>https://developer.android.com/guide/topics/providers/calendar-provider.html/#query</br></br> **Moreover applying strict mode to app would also reveal hotspots for possible I/O errors.**</br> https://developer.android.com/reference/android/os/StrictMode

**Comment by burhanrashid52** [comment]
Got it. It make sense now.
Can you please extract the content resovler logic into a seperate class and just expose `subscribe`,`unsubscirbe` and `creareFile` method which will be used in `EditImageActivity`.
Also need to resolve the conflicst as well.

**Comment by tanoDxyz** [comment]
@burhanrashid52 the conflicts are now  main problem - **Resolve Conflicts** button is disabled. and I will close the PR and Re-Open it if that helps

**Pull request closed without merging**
