### PR TITLE
Add test for correct alpha and color values

### PR DESCRIPTION
**Pull request by wasky**
This won't work until #505 is accepted.

### CODE REVIEW

**Comment by wasky** [comment]
@burhanrashid52 There's something wrong with CI build for this PR. It's running for over and hour now. Can you cancel the build manually?

**Comment by burhanrashid52** [comment]
> @burhanrashid52 There's something wrong with CI build for this PR. It's running for over and hour now. Can you cancel the build manually?

I am also not sure. Can you push something to re-run this ?

**Comment by wasky** [comment]
Everything's OK now, PR ready for review.

I split this PR into 4 commits for easier review. I suggest to review every commit separately.

**Comment by burhanrashid52** [comment]
@wasky Since we have moved some test in androidTest, I am not sure if those test will run in the CI because the `gradle test` only run unit tests.
Need to make changes in CI to run the test under `androidTest` as well.

**Comment by burhanrashid52** [comment]
> @wasky Since we have moved some test in androidTest, I am not sure if those test will run in the CI because the `gradle test` only run unit tests. Need to make changes in CI to run the test under `androidTest` as well.

Does `./gradlew check --stacktrace` run all the test in `photoEditor` ? Can you confirm?

**Comment by wasky** [comment]
`./gradlew test` runs tests in `test` folder. `./gradlew connectedCheck` runs tests in `androidTest` folder. Both tasks are executed by Github Actions. As a confirmation I created a new branch from this pull request in my forked repo and changed tests to fail. You can find the branch [here](https://github.com/wasky/PhotoEditor/commits/test-fail) and the results from tests [here](https://github.com/wasky/PhotoEditor/actions/runs/4036040306).

**Review by burhanrashid52 — APPROVED** [review]

**Pull request merged**
