### PR TITLE
AndroidX and Gradle update

### PR DESCRIPTION
**Pull request by DATL4G**
## Done
+ removed deprecated support libraries
+ added androidx libs
+ updated gradle version

## Not done yet
+ tested due to emulator problems

## Issue
#151

### CODE REVIEW

**Comment by burhanrashid52** [comment]
I've enabled the CI for PR now. So please push some changes to run the CI.

**Comment by burhanrashid52** [comment]
Thanks for the PR. Just thinking to have diffrent artifacts for photo editor for androidx support. Because if we do it in the same package then it will create an issue for the projects which are not migrated to AndroidX yet. What's your take on this ? @DATL4G

**Comment by DATL4G** [comment]
I understand the problem, and I think of **Jetifier**.
[Documentation](https://developer.android.com/studio/command-line/jetifier)
[Usage](https://developer.android.com/jetpack/androidx#using_androidx)
It would definitely be the faster solution (but maybe not the better one)

**Comment by MichelMelhem** [comment]
I really need to get androidX support, can you merge this please ?

**Comment by DATL4G** [comment]
@MichelMelhem
It's not mergable by now.
There are some conflicts in files wich were updated and i would have to resolve these.
And there is still the problem with merge it into master or like adding a new module or something like that for people who doesn't use AndroidX by now.
But you can use Jetifier (mentioned in above comment) to migrate support libraries in current master to androidx libraries

**Comment by DATL4G** [comment]
But if @burhanrashid52 would say "Lets merge that thing"
I would resolve the conflicts in no time

**Comment by MichelMelhem** [comment]
@DATL4G  okay

**Comment by burhanrashid52** [comment]
@DATL4G I did a poll for the need of AndroidX.
https://twitter.com/burhanrashid52/status/1191608242750648321
Seems like it's a good time to migrate to AndroidX. Thanks for the PR. Please resolve the conflict and rebase it from latest master than I'll be happy to merge your PR.

**Comment by burhanrashid52** [comment]
Thanks for the PR. I am preparing the release now. It make it live soon.

**Pull request merged**
