### PR TITLE
Add option for transparent sticker click through (PE-214)

### PR DESCRIPTION
**Pull request by lucianocheng**
Addresses issue PE-214.  Adds an option to be able to click-through views, so stickers that have alpha do not block stickers behind them.

https://github.com/burhanrashid52/PhotoEditor/issues/214

### CODE REVIEW

**Comment by burhanrashid52** [comment]
Thanks for the PR. I would suggest extracting the transparent logic part to separate class and inject that class as a dependency in MultiTouchListner. Please let me know your thoughts on this.

**Comment by lucianocheng** [comment]
Sounds good.  Inject as in use a DI framework or just make a static
instance?  Any thoughts to the transparent class name?

**Comment by burhanrashid52** [comment]
No DI framework. Just a manual instance injection. Is this just for sticker ? or for text and emoji also?

**Comment by lucianocheng** [comment]
> No DI framework. Just a manual instance injection.

Apologies but "manual instance injection" without a DI framework is still a bit unclear to me.  Do you mean adding it to the factory, making it a `static final`, adding it to the constructor, or something else?

> Is this just for sticker? or for text and emoji also? If this is just for sticker than StickerTransparecny might be work. It just a suggestion. Any better name is welcome.

Uses `View` opacity so it should work for anything.  I'll use `ViewTransparencyHelper` so it's clear that it's not an actual `View`.

**Comment by burhanrashid52** [comment]
Can you give me some steps to test this?

**Comment by burhanrashid52** [comment]
@lucianocheng Cannot merge because of conflict.

**Comment by lucianocheng** [comment]
I've changed my approach for this one. I'll close this one and recreate it.

**Comment by burhanrashid52** [comment]
@lucianocheng Do you have a plan for this to be done?

**Comment by lucianocheng** [comment]
Yes, I actually have this working but it's a huge change.

Essentially the editor has to keep track of a "mask" of each image that can be used to quickly calculate intersection. This mask must be updated whenever a user resizes an image.

The recalculation of the masks happens on a threadpool, and the storage happens within each MultiTouchListener. It can also sometimes slow down the editor or take up a good amount of memory to store the masks and update them.

I need to clean up the implementation a bit and figure out how to flag it. Also right now I create a threadpool on PhotoEditor and just pass it into MultiTouchListener, which is fine but not great.

**Comment by lucianocheng** [comment]
Biggest non-obvious problems with trying to solve this:

- Calculating intersection without a mask will make the editor lock up. Trying to get it to traverse the tree then "search" through the image to see if it intersects a alpha pixel is very slow and users will complain
- Traversing the view stack with the resize is very flaky. You can't trust getWidth() and getHeight() at all since the only thing that resizes is the scaling factor on the outer frame of the sticker. Snapshot is the only way to go that makes sense.
- You need a "radius" around each alpha pixel to account for finger width. Basically if a user is trying to select a thin sticker with alpha all around it, hitting it with your finger exactly is very difficult.

**Comment by lucianocheng** [comment]
@burhanrashid52 lets move further discussion over to the ticket #214

**Pull request closed without merging**
