### PR TITLE
Kotlin conversion of app+libraries

### PR DESCRIPTION
**Pull request by anderbytes**
New PR requested by maintainer, hope I got it right

### CODE REVIEW

**Comment by anderbytes** [comment]
@burhanrashid52 @lucianocheng 
Hope I didn't do anything wrong, I'm no expert at VCS

**Comment by anderbytes** [comment]
**Attention** @burhanrashid52 and @lucianocheng 

I tried doing some tests here and at the moment of the share, the FileURI created can't be reached. Probably I did something wrong with the FileProvider conversion, and I'm having trouble troubleshooting the cause.

Any of you can take a look?

**Comment by lucianocheng** [comment]
@anderbytes I'm happy to review code that works, but going back and forth on a single review is not a recipe for success.

If you are not confident that this PR is in good working order, I would propose we go back to my original suggestion and submit smaller PRs with smaller changes.

Either way let's wait for @burhanrashid52 to figure out what's going on with GitHub actions not running first.

**Comment by anderbytes** [comment]
I'll now use my little free time to focus on my personal projects. Good luck for you guys. Hope you find someone better at testing.

**Pull request closed without merging**
