### PR TITLE
Added customization option for frame color and improved callbaks

### PR DESCRIPTION
**Pull request by Endhuine**
In order to satisfy my need in a project, i've made a few change:

the builder have now the option to set a different drawable for the close icon of the stiker and to set a differet color for the frame.

In some callback I've added the view in return, so if you add/remove you know what view is being removed/added; Same way goes for the addText/Image/Emoji, these now return the view that has been added to the editing.

Maybe it'll be useful to other user. 
Have a nice day

### CODE REVIEW

**Comment by burhanrashid52** [comment]
Just thinking what will be a better solution to provide `TextView` attribute builder ? or return `TextView` on `addText()` ? @Endhuine @perezfer @Agfct

**Comment by perezfer** [comment]
In practise, both approaches work similar for the general use and it might be more like a matter of taste.
There is one main difference.
If you return the TextView instance from addText method, the client can still modify the attributes and that's it:
(Example)
TextView textView = photoEditor.addText(myText);
textView.setTextSize(12.0f);

On the other side, if you let the client pass its own instance of the textView, this instance can be a subclass, which makes it more flexible.
(Example)
TextView myFancyTextView = new ThreeDimensionalTextView();
builder.addText(myFancyTextView);

In similar conditions I would prefer the second approach because it is more flexible. The only reason why I would justify to force the instance to be just a TextView is to prevent the library from having an unexpected behaviour due to wrong implementations of a TextView subclass.

I hope this helps and that I understood the question.

**Comment by Endhuine** [comment]
I'd prefer the builder approach too. The only reason I make it return from the addText was not to break the api. But since I've modified the callbacks too, the "I'd not break the api" is no more.

**Comment by burhanrashid52** [comment]
Done in 0.4.0 release #152

**Pull request closed without merging**
